version: '2'
services:
    gaffelcup-app:
        image: gaffelcup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gaffelcup-mysql:3306/gaffelcup?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gaffelcup-mysql:
        extends:
            file: mysql.yml
            service: gaffelcup-mysql
